name: Install 7zip-zstd codecs
description: Installs 7zip-zstd codecs
inputs:
  version:
    description: Version of 7zip-zstd codecs to install
    required: false
    default: 22.01-v1.5.5-R3
runs:
  using: composite
  steps:
    - if: runner.os != 'Windows'
      shell: pwsh
      run: exit 1
    - shell: pwsh
      run: |
        aria2c -x 16 "https://github.com/mcmilk/7-Zip-zstd/releases/download/v${{ inputs.version }}/Codecs-x64.7z"
        7z x Codecs-x64.7z "-o$((Get-Item $((Get-Command 7z).Path)).Directory.FullName)\Codecs"
        rm Codecs-x64.7z
