name: Build

on:
  workflow_call:
    inputs:
      x86:
        required: false
        default: false
        type: boolean
    outputs:
      finished:
        value: ${{ jobs.build-12.outputs.finished }}

jobs:
  build-1: { name: '1/12', uses: './.github/workflows/step.yml', with: { num: 1, finished: false, first: true, x86: '${{ inputs.x86 }}' } }
  build-2: { name: '2/12', needs: build-1, uses: './.github/workflows/step.yml', with: { num: 2, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-3: { name: '3/12', needs: build-2, uses: './.github/workflows/step.yml', with: { num: 3, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-4: { name: '4/12', needs: build-3, uses: './.github/workflows/step.yml', with: { num: 4, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-5: { name: '5/12', needs: build-4, uses: './.github/workflows/step.yml', with: { num: 5, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-6: { name: '6/12', needs: build-5, uses: './.github/workflows/step.yml', with: { num: 6, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-7: { name: '7/12', needs: build-6, uses: './.github/workflows/step.yml', with: { num: 7, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-8: { name: '8/12', needs: build-7, uses: './.github/workflows/step.yml', with: { num: 8, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-9: { name: '9/12', needs: build-8, uses: './.github/workflows/step.yml', with: { num: 9, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-10: { name: '10/12', needs: build-9, uses: './.github/workflows/step.yml', with: { num: 10, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-11: { name: '11/12', needs: build-10, uses: './.github/workflows/step.yml', with: { num: 11, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }
  build-12: { name: '12/12', needs: build-11, uses: './.github/workflows/step.yml', with: { num: 12, finished: "${{ join(needs.*.outputs.finished) == 'true' }}", x86: '${{ inputs.x86 }}' } }