name: Step

on:
  workflow_call:
    inputs:
      finished:
        required: true
        type: boolean
      first:
        required: false
        default: false
        type: boolean
      x86:
        required: false
        default: false
        type: boolean
      num:
        required: false
        default: -1
        type: number
    outputs:
      finished:
        value: ${{ inputs.finished || jobs.pt1.outputs.finished }}

jobs:
  pt1:
    name: ${{ inputs.x86 && 'x86 build' || 'x64 build' }}, step ${{ inputs.num }}, preparation
    if: '!inputs.finished'
    runs-on: windows-latest
    steps:
      - run: Get-PSDrive

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy ungoogled-chromium stuff to C drive
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pnpm-store-

      - name: Setup third-party tool cache
        uses: actions/cache@v3
        with:
          path: |
            C:/ungoogled-chromium-windows/build/download_cache
            C:/ungoogled-chromium-windows/build/src/third_party
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-downloads-${{ hashFiles('**/downloads.ini', '**/chromium_version.txt') }}

      - name: Setup PGO profile cache
        uses: actions/cache@v3
        with:
          path: '**.profdata'
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pgo-${{ hashFiles('**.profdata') }}

      - name: Install node.js dependencies
        run: pnpm install
        working-directory: ./.github/actions/stage

      - name: Run stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ inputs.finished }}
          from_artifact: ${{ !inputs.first }}
          x86: ${{ inputs.x86 }}

      - name: Copy PGO profile to workspace for caching
        run: Copy-Item -Path C:/ungoogled-chromium-windows -Filter *.profdata -Destination $env:GITHUB_WORKSPACE -Recurse
    outputs:
      finished: ${{ steps.stage.outputs.finished }}