name: Step

on:
  workflow_call:
    inputs:
      finished:
        required: true
        type: boolean
      first:
        required: false
        default: false
        type: boolean
      x86:
        required: false
        default: false
        type: boolean
    outputs:
      finished:
        value: ${{ jobs.reusable_workflow_job.outputs.finished }}

jobs:
  reusable_workflow_job:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ inputs.finished }}
          from_artifact: ${{ !inputs.first }}
          x86: ${{ inputs.x86 }}
    outputs:
      finished: ${{ steps.stage.outputs.finished }}