name: Build ungoogled-chromium single step

on:
  workflow_call:
    inputs:
      finished:
        required: true
        type: boolean
      first:
        required: false
        default: false
        type: boolean
      x86:
        required: false
        default: false
        type: boolean
      num:
        required: false
        default: -1
        type: number
    outputs:
      finished:
        value: ${{ inputs.finished || jobs.pt1.outputs.finished }}

jobs:
  pt1:
    name: step ${{ inputs.num }}
    if: '!inputs.finished'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    env:
      SEVENZ_PATH: unset fixme
      CACHE_PREFIX: ${{ matrix.os }}
      PROJECT_LOCATION: C:\ungoogled-chromium-windows
      ARCH_STRING: ${{ inputs.x86 && 'x86' || 'x64' }}
      TIMEOUT_KEY: step
    steps:
      - name: Download previously compiled LLVM
        uses: actions/download-artifact@v3
        with:
          name: chromium-llvm
          path: ${{ env.PROJECT_LOCATION }}\build\src\third_party\llvm-build

      - id: common-setup
        uses: ./.github/actions/common-setup
        with:
          sccache-key: chromium
          os: ${{ matrix.os }}
          arch: ${{ env.ARCH_STRING }}
          project-location: ${{ env.PROJECT_LOCATION }}

      - name: Setup environment
        id: setup-environment
        uses: ./.github/actions/stage
        with:
          tarball-artifact-name: build-artifact-${{ env.ARCH_STRING }}
          tarball-root: .\build
          tarball-pattern: .\build\src
          cwd: ${{ env.PROJECT_LOCATION }}
          run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step setup-environment
          key: ${{ env.TIMEOUT_KEY }}

      - name: Download PGO profiles
        uses: ./.github/actions/stage
        with:
          tarball-artifact-name: build-artifact-${{ env.ARCH_STRING }}
          tarball-root: .\build
          tarball-pattern: .\build\src
          cwd: ${{ env.PROJECT_LOCATION }}
          run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step download-pgo-profiles
          key: ${{ env.TIMEOUT_KEY }}

      - name: Create ARGS.gn
        uses: ./.github/actions/stage
        with:
          tarball-artifact-name: build-artifact-${{ env.ARCH_STRING }}
          tarball-root: .\build
          tarball-pattern: .\build\src
          cwd: ${{ env.PROJECT_LOCATION }}
          run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step create-args-gn
          key: ${{ env.TIMEOUT_KEY }}

      - name: Bootstrap GN
        uses: ./.github/actions/stage
        with:
          tarball-artifact-name: build-artifact-${{ env.ARCH_STRING }}
          tarball-root: .\build
          tarball-pattern: .\build\src
          cwd: ${{ env.PROJECT_LOCATION }}
          run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step bootstrap-gn
          key: ${{ env.TIMEOUT_KEY }}

      - name: Build
        id: stage
        uses: ./.github/actions/stage
        with:
          tarball-artifact-name: build-artifact-${{ env.ARCH_STRING }}
          tarball-root: ${{ env.PROJECT_LOCATION }}\build
          tarball-pattern: ${{ env.PROJECT_LOCATION }}\build\src
          cwd: ${{ env.PROJECT_LOCATION }}
          run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step build
          ignore-exit-codes: 124

      - name: Package build result
        if: steps.stage.outputs.outcome == 'success'
        run: python -u build.py --ci --7z-path "${{steps.common-setup.outputs.sevenz-actual-path}}\7z.exe" --step package
        working-directory: ${{ env.PROJECT_LOCATION }}

      - name: Upload build result
        if: steps.stage.outputs.outcome == 'success'
        uses: ./.github/actions/upload-chromium-package
        with:
          x86: ${{ inputs.x86 }}
          project-location: ${{ env.PROJECT_LOCATION }}

    outputs:
      finished: ${{ steps.stage.outputs.outcome == 'success' }}