name: Step

on:
  workflow_call:
    inputs:
      finished:
        required: true
        type: boolean
      first:
        required: false
        default: false
        type: boolean
      x86:
        required: false
        default: false
        type: boolean
      num:
        required: false
        default: -1
        type: number
    outputs:
      finished:
        value: ${{ jobs.reusable_workflow_job.outputs.finished }}

jobs:
  reusable_workflow_job:
    name: ${{ inputs.x86 && 'x86 build' || 'x64 build' }}, step ${{ inputs.num }}
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        if: '!inputs.finished'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy repository to expected location
        if: '!inputs.finished'
        run: |
          Set-Location -Path C:\
          Move-Item -Path $env:GITHUB_WORKSPACE -Destination "C:\ungoogled-chromium-windows"
          Set-Location -Path C:\ungoogled-chromium-windows

      - name: Install pnpm
        if: '!inputs.finished'
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        if: '!inputs.finished'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: '!inputs.finished'
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pnpm-store-

      - name: Setup third-party tool cache
        if: '!inputs.finished'
        uses: actions/cache@v3
        with:
          path: |
            ./build/download_cache
            ./build/src/third_party
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-downloads-${{ hashFiles('**/downloads.ini', '**/chromium_version.txt') }}

      - name: Setup PGO profile cache
        if: '!inputs.finished'
        uses: actions/cache@v3
        with:
          path: '**.profdata'
          key: ${{ runner.os }}-${{ inputs.x86 && 'x86' || 'x64' }}-pgo-${{ hashFiles('**.profdata') }}

      - name: Install node.js dependencies
        if: '!inputs.finished'
        run: pnpm install
        working-directory: ./.github/actions/stage

      - name: Run stage
        if: '!inputs.finished'
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ inputs.finished }}
          from_artifact: ${{ !inputs.first }}
          x86: ${{ inputs.x86 }}
    outputs:
      finished: ${{ inputs.finished || steps.stage.outputs.finished }}